// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6sZXyzbEj3B88U_F6peicrTS7qBCJRr4',
    appId: '1:1075738146221:web:142b7ac12759862cce9d24',
    messagingSenderId: '1075738146221',
    projectId: 'localevents-25346',
    authDomain: 'localevents-25346.firebaseapp.com',
    storageBucket: 'localevents-25346.firebasestorage.app',
    measurementId: 'G-JESW234HMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDzl5NLPKyiyH-uxuHfTDodGsHe1EjKW8',
    appId: '1:1075738146221:android:f704bcd2d16cdd42ce9d24',
    messagingSenderId: '1075738146221',
    projectId: 'localevents-25346',
    storageBucket: 'localevents-25346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4OyPTd85UcyBU5OwHqgaF3pL92q_QRec',
    appId: '1:1075738146221:ios:fa44f8de50ad6260ce9d24',
    messagingSenderId: '1075738146221',
    projectId: 'localevents-25346',
    storageBucket: 'localevents-25346.firebasestorage.app',
    iosBundleId: 'com.example.localEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4OyPTd85UcyBU5OwHqgaF3pL92q_QRec',
    appId: '1:1075738146221:ios:fa44f8de50ad6260ce9d24',
    messagingSenderId: '1075738146221',
    projectId: 'localevents-25346',
    storageBucket: 'localevents-25346.firebasestorage.app',
    iosBundleId: 'com.example.localEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6sZXyzbEj3B88U_F6peicrTS7qBCJRr4',
    appId: '1:1075738146221:web:9c394cce5e640a15ce9d24',
    messagingSenderId: '1075738146221',
    projectId: 'localevents-25346',
    authDomain: 'localevents-25346.firebaseapp.com',
    storageBucket: 'localevents-25346.firebasestorage.app',
    measurementId: 'G-HR1TE4B6V3',
  );
}
